version: '3'
services:
  web:
    depends_on:
      - mysql
    build: 
      context: .
      args: 
        - PORT=4000
        - SQL_HOST=localhost
        - SQL_HOST_READ=0.0.0.0
        - SQL_HOST_WRITE=0.0.0.0
        - SQL_PORT=3306
        - SQL_DB=test-db
        - SQL_USER=Add your user
        - SQL_PASS=Add your Password
        - SQL_DIALECT=mysql
        - SQL_POOL_LIMIT=100
    restart: always
    ports:
      - "4000:4000"